name: flow_matching
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.4.0
      - accelerate==0.28.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - asciitree==0.3.3
      - astroid==4.0.4
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - beautifulsoup4==4.14.3
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cmake==4.2.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - cycler==0.12.1
      - datasets==4.1.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - deepdiff==8.6.1
      - diffusers==0.18.2
      - dill==0.4.1
      - dm-control==1.0.20
      - dm-env==1.6
      - dm-tree==0.1.9
      - draccus==0.10.0
      - egl-probe==1.0.2
      - einops==0.8.2
      - etils==1.13.0
      - evdev==1.9.3
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fasteners==0.20
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - grpcio==1.78.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==1.2.3
      - h11==0.16.0
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.23.4
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - inquirerpy==0.3.4
      - iopath==0.1.10
      - ipykernel==7.2.0
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - isort==7.0.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonlines==4.0.0
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - lxml==6.0.2
      - mako==1.3.10
      - markdown==3.10.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mccabe==0.7.0
      - mergedeep==1.3.4
      - mink==0.0.5
      - mpmath==1.3.0
      - mujoco==3.1.6
      - multidict==6.7.1
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.63.1
      - numcodecs==0.13.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - osfclient==0.0.5
      - pandas==2.3.3
      - parso==0.8.6
      - pastel==0.2.1
      - peft==0.10.0
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - poethepoet==0.10.0
      - portalocker==3.2.0
      - pot==0.9.6.post1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==23.0.0
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygame==2.6.1
      - pygments==2.19.2
      - pylint==4.0.4
      - pymunk==6.5.1
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.3.2
      - pyserial==3.5
      - pysocks==1.7.1
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytorch-lightning==1.9.5
      - pytorch3d==0.7.8
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - pyzmq==27.1.0
      - qpsolvers==4.8.2
      - quadprog==0.1.13
      - regex==2026.1.15
      - requests==2.32.5
      - rerun-sdk==0.26.2
      - robomimic==0.3.0
      - robosuite==1.5.2
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scikit-video==1.1.11
      - scipy==1.15.3
      - sentry-sdk==2.52.0
      - setuptools==80.10.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.3.0
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.4.0
      - tomlkit==0.14.0
      - torch==2.2.2+cu121
      - torchaudio==2.2.2+cu121
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchcodec==0.5
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.8.2
      - torchsde==0.2.6
      - torchvision==0.17.2+cu121
      - tornado==6.5.4
      - tqdm==4.67.3
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.41.2
      - triton==2.2.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - wandb==0.24.2
      - wcwidth==0.6.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - wrapt==2.1.1
      - xxhash==3.6.0
      - yacs==0.1.8
      - yarl==1.22.0
      - zarr==2.18.3
      - zipp==3.23.0
prefix: /home/yanan/anaconda3/envs/flow_matching
